[package]
name = "rpi-mpu9250-sc"
version = "0.1.0"
authors = ["niklas adam"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rosc = "0.4.0"
linux-embedded-hal = "0.3.0"
madgwick = "0.1.1"
mpu9250-i2c = "0.6.6"
